config/routes.rb
Rails.application.routes.draw do

  resources :logs

  resources :admin_settings

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    match 'users/:id/show', to: 'users/registrations#show', via: :get, as: "user_show"
    match 'users/', to: 'users/registrations#index', via: :get, as: "users_index"
    match 'users/:id/admin_edit', to: 'users/registrations#admin_edit', via: :get, as: "user_admin_edit"
    match 'users/:id/admin_update', to: 'users/registrations#admin_update', via: :patch, as: "user_admin_update"
  end

  #get 'users/:id', to: 'users/registrations#show'

  #match '/users/:id', to: 'users/registrations#show', via: :get

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_setting.rb
class AdminSetting < ApplicationRecord
  validates :title, :value, presence: true

  validates :title, format: { with: /\A[a-zA-Zs\s]+\z/,
    message: "only allows letters" }

  validates :title, length: { in: 4..20 }

  validates :value, uniqueness: true
  #validates :value, presence: true
  #add bad symbols validation yes
end

app/controllers/admin_settings_controller.rb
class AdminSettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_admin_setting, only: [:show, :edit, :update, :destroy]

  # GET /admin_settings
  # GET /admin_settings.json
  def index
    @admin_settings = AdminSetting.all
  end

  # GET /admin_settings/1
  # GET /admin_settings/1.json
  def show
  end

  # GET /admin_settings/new
  def new
    @admin_setting = AdminSetting.new
  end

  # GET /admin_settings/1/edit
  def edit
  end

  # POST /admin_settings
  # POST /admin_settings.json
  def create
    @admin_setting = AdminSetting.new(admin_setting_params)
    #byebug
    @admin_setting.alias = @admin_setting.title.downcase.split(' ').join('_')

    respond_to do |format|
      if @admin_setting.save
        format.html { redirect_to @admin_setting, notice: 'Admin setting was successfully created.' }
        format.json { render :show, status: :created, location: @admin_setting }
      else
        format.html { render :new }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_settings/1
  # PATCH/PUT /admin_settings/1.json
  def update
    respond_to do |format|
      if @admin_setting.update(admin_setting_params)
        format.html { redirect_to @admin_setting, notice: 'Admin setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_setting }
      else
        format.html { render :edit }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_settings/1
  # DELETE /admin_settings/1.json
  def destroy
    @admin_setting.destroy
    respond_to do |format|
      format.html { redirect_to admin_settings_url, notice: 'Admin setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_setting
      @admin_setting = AdminSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_setting_params
      params.require(:admin_setting).permit(:title, :alias, :value, :description, :for)
    end

    def check_admin
      if current_user.workgroup != 'Administrators'
        redirect_back fallback_location: 'home#index'
        flash[:notice] = "Access to Settings denied"
      end
    end

end

app/helpers/admin_settings_helper.rb
module AdminSettingsHelper
end

app/views/admin_settings/_form.html.erb
<%= form_with(model: admin_setting, local: true) do |form| %>
  <% if admin_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% admin_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :admin_setting_title %>
  </div>

  <div class="field">
    <%= form.label :alias, 'generate automatically (will be hidden)' %>
    <%= form.text_field :alias, id: :admin_setting_alias, disabled: true %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :admin_setting_value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :admin_setting_description %>
  </div>

  <div class="field">
    <%= form.label :for %>
    <%= form.text_field :for, id: :admin_setting_for %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_settings/edit.html.erb
<h1>Editing Admin Setting</h1>

<%= render 'form', admin_setting: @admin_setting %>

<%= link_to 'Show', @admin_setting %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Settings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Alias</th>
      <th>Value</th>
      <th>Description</th>
      <th>For</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_settings.each do |admin_setting| %>
      <tr>
        <td><%= admin_setting.title %></td>
        <td><%= admin_setting.alias %></td>
        <td><%= admin_setting.value %></td>
        <td><%= admin_setting.description %></td>
        <td><%= admin_setting.for %></td>
        <!--<td><%# link_to 'Show', admin_setting %></td>-->
        <td><%= link_to 'Edit', edit_admin_setting_path(admin_setting) %></td>
        <!--<td><%# link_to 'Destroy', admin_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Setting', new_admin_setting_path %>

app/views/admin_settings/new.html.erb
<h1>New Admin Setting</h1>

<%= render 'form', admin_setting: @admin_setting %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_setting.title %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @admin_setting.alias %>
</p>

<p>
  <strong>Value:</strong>
  <%= @admin_setting.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_setting.description %>
</p>

<p>
  <strong>For:</strong>
  <%= @admin_setting.for %>
</p>

<%= link_to 'Edit', edit_admin_setting_path(@admin_setting) %> |
<%= link_to 'Back', admin_settings_path %>