config/routes.rb
Rails.application.routes.draw do

  resources :logs

  resources :admin_settings

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    match 'users/:id/show', to: 'users/registrations#show', via: :get, as: "user_show"
    match 'users/', to: 'users/registrations#index', via: :get, as: "users_index"
    match 'users/:id/admin_edit', to: 'users/registrations#admin_edit', via: :get, as: "user_admin_edit"
    match 'users/:id/admin_update', to: 'users/registrations#admin_update', via: :patch, as: "user_admin_update"
  end

  #get 'users/:id', to: 'users/registrations#show'

  #match '/users/:id', to: 'users/registrations#show', via: :get

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/log.rb
class Log < ApplicationRecord
  paginates_per 12
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    #@logs = Log.all
    @logs = Log.order('id DESC').page(params[:page])
    #@logs = Log.order(:id).page(params[:page])
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    #byebug
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
    #byebug
    #check_archive_depth
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:who, :head, :body, :level)
      #byebug
    end

    def check_admin
      if current_user.workgroup != 'Administrators'
        redirect_back fallback_location: 'home#index'
        flash[:notice] = "Access to Settings denied"
      end
    end

    #def check_archive_depth
    #  byebug
    #end
end

app/helpers/logs_helper.rb
module LogsHelper

  def who_present(id)
    if User.exists?(id)
      link_to User.find(id).name, user_show_path(id), :class => "btn-link"
    else
      "User was deleted"
    end
  end

  def check_archive_depth
      #byebug
      logs = Log.all
      depth = AdminSetting.where(:alias == 'logs_archive_depth')[0].value.to_i
      if logs.size > depth
        diff = logs.size - depth
        for i in 0..(diff-1)
          logs[i].delete
        end
      end
  end

  def log_record(head, user_id)
    log = Log.new
    #byebug
    log.who = user_id
    log.head = head
    log.level = 1
    log.save
    check_archive_depth
  end

end

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :who %>
    <%= form.text_field :who, id: :log_who %>
  </div>

  <div class="field">
    <%= form.label :head %>
    <%= form.text_field :head, id: :log_head %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :log_body %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :log_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Logs</h1>

<%= paginate @logs, :theme => 'twitter-bootstrap-3' %>

<table class="table">
  <thead>
    <tr>
      <th>Who</th>
      <th>Head</th>
      <th>Body</th>
      <th>Level</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= who_present(log.who) %></td>
        <td><%= log.head %></td>
        <td><%= log.body %></td>
        <td><%= log.level %></td>
        <td><%= log.created_at %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Who:</strong>
  <%= @log.who %>
</p>

<p>
  <strong>Head:</strong>
  <%= @log.head %>
</p>

<p>
  <strong>Body:</strong>
  <%= @log.body %>
</p>

<p>
  <strong>Level:</strong>
  <%= @log.level %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>