config/routes.rb
Rails.application.routes.draw do

  resources :logs

  resources :admin_settings

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    match 'users/:id/show', to: 'users/registrations#show', via: :get, as: "user_show"
    match 'users/', to: 'users/registrations#index', via: :get, as: "users_index"
    match 'users/:id/admin_edit', to: 'users/registrations#admin_edit', via: :get, as: "user_admin_edit"
    match 'users/:id/admin_update', to: 'users/registrations#admin_update', via: :patch, as: "user_admin_update"
  end

  #get 'users/:id', to: 'users/registrations#show'

  #match '/users/:id', to: 'users/registrations#show', via: :get

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserShowProjectTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= nav_bar fixed: :top, brand: "SYSTOP PM", responsive: true, container: false do %>
    <% if user_signed_in? %>
        <%= menu_group do %>
            <%= menu_item "Home", root_path %>
            <%= menu_divider %>
            <% if current_user.workgroup == 'Administrators' %>
              <%= drop_down "Admin Settings" do %>
                  <%= menu_item 'Logs', logs_path %>
                  <%= menu_item 'Admin Settings', admin_settings_path %>
                  <%= menu_item 'Users', users_index_path %>
              <% end %>
            <% end %>
        <% end %>
        <%= menu_group pull: :right do %>
                <%= menu_item current_user.name, user_show_path(current_user.id)%>
                <%= menu_item 'Выйти', destroy_user_session_path, :method => :delete %>

        <% end %>
      <% end %>
    <% end %>


    <br><br>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>